import os
import yaml
from pathlib import Path
from datetime import datetime
import typer
from rich.console import Console

app = typer.Typer(help="Vault Manager: Manipulate the Obsidian Blueprint programmatically")
console = Console()

# The vault directory is located one level up from the backend directory
VAULT_DIR = Path(__file__).resolve().parent.parent / "vault"

@app.command()
def create_folder(path: str):
    """Programmatically create a new folder structurally inside the vault."""
    target_path = VAULT_DIR / path
    if target_path.exists():
        console.print(f"[bold yellow]Folder already exists: {target_path}[/bold yellow]")
        return
    
    try:
        target_path.mkdir(parents=True, exist_ok=True)
        console.print(f"[bold green]Successfully created folder: {target_path}[/bold green]")
        
        # Add a README standard to initialize the folder
        readme_path = target_path / "README.md"
        if not readme_path.exists():
            readme_path.write_text(f"# {target_path.name}\n\nFolder automatically generated by Vault Manager.", encoding="utf-8")
    except Exception as e:
        console.print(f"[bold red]Failed to create folder: {e}[/bold red]")


@app.command()
def inject_template(template_name: str, target_file: str, title: str = "New Document"):
    """Inject an AI YAML template into a new markdown file."""
    template_path = VAULT_DIR / "80_Templates" / template_name
    
    if not template_path.exists():
        console.print(f"[bold red]Template not found: {template_path}[/bold red]")
        raise typer.Exit(code=1)
        
    output_path = VAULT_DIR / target_file
    if output_path.exists():
        console.print(f"[bold yellow]Target file already exists: {output_path}[/bold yellow]")
        raise typer.Exit(code=1)
        
    # Read template content
    with open(template_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Basic token replacement
    content = content.replace("{{date}}", datetime.now().strftime("%Y-%m-%d"))
    content = content.replace("{{title}}", title)
    
    # Write to target destination
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
        
    console.print(f"[bold green]Successfully generated {target_file} using {template_name}[/bold green]")


@app.command()
def update_moc(moc_filename: str, title: str, doc_reference: str):
    """Update a Map of Content (MOC) with a new interlinked entry."""
    full_path = VAULT_DIR / "00_MOCs" / moc_filename
    
    if not full_path.exists():
        console.print(f"[bold red]MOC not found: {full_path}[/bold red]")
        raise typer.Exit(code=1)
        
    with open(full_path, "r+", encoding="utf-8") as f:
        content = f.read()
        
        # Check if entry already exists to prevent duplicates
        if f"[[{doc_reference}]]" in content or title in content:
            console.print(f"[bold yellow]Reference already exists in MOC: {title}[/bold yellow]")
            return
            
        # Append the new link
        entry = f"\n- [[{doc_reference}]] - {title}"
        f.write(entry)
        
    console.print(f"[bold green]Successfully appended {title} to {moc_filename}[/bold green]")


if __name__ == "__main__":
    app()
